# docker-compose.prod.yml
services:
  redis:
    container_name: redis-prod
    volumes:
      - redis-data-prod:/data
    command: redis-server --appendonly yes
  app:
    environment:
    - APP_ENV=prod

volumes:
  redis-data-prod:
